// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"database/sql"
	"time"
)

type Shift struct {
	ID               int32
	Created          time.Time
	Uid              string
	WorkDate         time.Time
	ShiftLengthHours float64
	UserID           int32
	Updated          sql.NullTime
	Deleted          sql.NullTime
}

type User struct {
	ID        int32
	Created   time.Time
	Uid       string
	Type      sql.NullString
	FirstName string
	LastName  string
	Email     string
	Password  string
	Updated   time.Time
	Deleted   sql.NullTime
}
